services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"
  apache_php:
    container_name: MyFirstBlogPHP-PhpApache
    image: webhippie/php-apache
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      APACHE_WEBROOT: /srv/www/public
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      MAIL_FROM_EMAIL: no-reply@mon-site.test
      MAIL_FROM_NAME: Mon Site
    depends_on:
      - mailhog
    volumes:
      - ./:/srv/www
  mysql:
    container_name: MyFirstBlogPHP-Mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ../MYSQL-MyFirstBlog/DATA:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123user
  phpmyadmin:
    container_name: MyFirstBlogPHP-PhpMyadmin
    image: phpmyadmin
    ports:
      - "8088:80"
    environment:
      - PMA_HOSTS=mysql